services:
  php:
    build:
      context: .
      dockerfile: deployment/development/php/Dockerfile
    container_name: ss-notifier-api
    ports:
      - "${PHP_PORT:-9000}:9000"
    volumes:
      - ./ss-notifier-api:/var/www/html
      - ./deployment/development/php/www.dev.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./deployment/development/php/php.ini:/usr/local/etc/php/php.ini:ro
    restart: "no"
    depends_on:
      - pgsql
      - redis
    networks:
      - ss-notifier-network

  nginx:
    build:
      context: deployment/development/nginx
    container_name: ss-notifier-nginx
    ports:
      - "${NGINX_PORT:-8080}:80"
    depends_on:
      - php
    volumes:
      - ./ss-notifier-api:/var/www/html
    networks:
      - ss-notifier-network
    restart: "no"

  web:
    build: 
      context: .
      dockerfile: deployment/development/web/Dockerfile
    container_name: ss-notifier-web
    ports:
      - "${WEB_PORT:-3001}:3000"
    volumes:
       - ./ss-notifier-web:/app
    networks:
      - ss-notifier-network
    restart: "unless-stopped"

  pgsql:
    image: postgres:18.0
    container_name: ss-notifier-pgsql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PGSQL_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ss-notifier-network
    restart: "unless-stopped"

  redis:
    image: redis:8.2.1
    container_name: ss-notifier-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - ss-notifier-network
    restart: "unless-stopped"


  php-worker:
    build:
      context: deployment/development/php-worker
    container_name: ss-notifier-php-worker
    volumes:
      - ./ss-notifier-api:/var/www/html
    depends_on:
      - php
      - pgsql
      - redis
    networks:
      - ss-notifier-network
    restart: "unless-stopped"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4
    container_name: ss-notifier-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    networks:
      - ss-notifier-network
    restart: "unless-stopped"
      
  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4
    container_name: ss-notifier-kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KIBANA_ENCRYPTION_KEY}
    volumes:
      - ./deployment/development/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    depends_on:
      - elasticsearch
    networks:
      - ss-notifier-network
    restart: "unless-stopped"

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.1.4
    container_name: ss-notifier-filebeat
    volumes:
      - ./deployment/development/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./ss-notifier-api/storage/logs:/var/www/html/storage/logs:ro
      - filebeat_data:/usr/share/filebeat/data
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - elasticsearch
      - kibana
      - php-worker
    networks:
      - ss-notifier-network
    restart: "unless-stopped"

networks:
  ss-notifier-network:
    name: ss-notifier-network

volumes:
  postgres_data:
  elasticsearch_data:
  filebeat_data:
